require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'onub2bmobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :production => false,
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :ios_deployment_target => min_ios_version_supported
  )

  target 'onub2bmobileTests' do
    inherit! :complete
    post_install do |installer|
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false,
        :ccache_enabled => true
      )
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'FB_SONARKIT_ENABLED=1',
        ]
      end
    end
  end
end
